root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: true
homepage:
    path:   /{_locale}
    defaults: { _controller: AppBundle:Default:home}
    requirements:
        _locale: ro|en
db_test:
    path:      /db
    defaults:  { _controller: AppBundle:Dbtest:index }
story_list:
    path:     /{_locale}/story
    defaults: { _controller: AppBundle:Default:list }
    requirements:
        _locale: ro|en
story_show:
    path:      /{_locale}/story/{no}
    defaults:  { _controller: AppBundle:Default:show}
    requirements:
        _locale: ro|en
argument:
    path:     /{_locale}/argument
    defaults: { _controller: AppBundle:Default:argument }
    requirements:
        _locale: ro|en
login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }
admin:
    path: /admin
    defaults: { _controller: AppBundle:Admin:admin }
logout:
    path: /logout
admin_story_edit:
    path: /admin/story/{no}/edit
    defaults: { _controller: AppBundle:Admin:edit }
admin_story_add:
    path: /admin/story/add
    defaults: { _controller: AppBundle:Admin:add }
admin_photo_add:
    path: /admin/photo/add
    defaults: { _controller: AppBundle:Admin:photoadd }
